# Generated by Django 2.2.3 on 2020-05-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link_image', models.CharField(max_length=400)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq de perguntas e respostas'},
        ),
    ]
