# Generated by Django 2.2.3 on 2020-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20200504_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_amazon',
            field=models.CharField(default='EEE', max_length=100),
            preserve_default=False,
        ),
    ]
